### ISSUE TITLE
Fix GSON not availble warning in feature.xml

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1267]
![image](https://cloud.githubusercontent.com/assets/10523105/22179571/d2fce61a-e025-11e6-8d1d-4b5cc76597d3.png)

Turns out that the Maven artifact version is `2.7`, but its OGSi version is `2.7.0`.

- `pom.xml`:
```xml
    <dependency>
      <!-- bundle: com.google.gson -->
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.7</version>
    </dependency>
```

- Excerpt from `MANIFEST.MF` of `gson`:
```yaml
Export-Package: com.google.gson;uses:="com.google.gson.reflect,com.goo
 gle.gson.stream";version="2.7.0",com.google.gson.annotations;version=
 "2.7.0",com.google.gson.reflect;version="2.7.0",com.google.gson.strea
 m;version="2.7.0"
Bundle-Name: Gson
Bundle-Version: 2.7.0
```
